services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: archon-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-archon_dev}
      POSTGRES_USER: ${POSTGRES_USER:-archon_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-archon_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - archon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-archon_user} -d ${POSTGRES_DB:-archon_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: archon-redis
    ports:
      - "6379:6379"
    networks:
      - archon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: archon-backend
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL_DEV=postgresql://${POSTGRES_USER:-archon_user}:${POSTGRES_PASSWORD:-archon_password}@postgres:5432/${POSTGRES_DB:-archon_dev}
      - DATABASE_URL_ADMIN_DEV=postgresql://${POSTGRES_USER:-archon_user}:${POSTGRES_PASSWORD:-archon_password}@postgres:5432/${POSTGRES_DB:-archon_dev}
      - ARCHON_SERVICE_TYPE=development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    networks:
      - archon-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload


  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: archon-frontend
    environment:
      - VITE_API_URL=http://backend:8000
      - VITE_WS_API_URL=ws://backend:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - archon-network
    depends_on:
      - backend
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0

volumes:
  postgres_data:
    driver: local

networks:
  archon-network:
    driver: bridge
